
package com.offcn;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* serviceService service = new serviceService();
* Service portType = service.getServicePort();
* portType.getValue(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "serviceService", targetNamespace = "http://offcn.com/", wsdlLocation = "http://localhost:9101/Service/hello?wsdl")
public class ServiceService extends javax.xml.ws.Service {

	private final static URL SERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.offcn.ServiceService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.offcn.ServiceService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:9101/Service/hello?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:9101/Service/hello?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICESERVICE_WSDL_LOCATION = url;
	}

	public ServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceService() {
		super(SERVICESERVICE_WSDL_LOCATION, new QName("http://offcn.com/", "serviceService"));
	}

	/**
	 * 
	 * @return returns Service
	 */
	@WebEndpoint(name = "servicePort")
	public com.offcn.Service getServicePort() {
		return super.getPort(new QName("http://offcn.com/", "servicePort"), Service.class);
	}

}
